# Gitleaks configuration for ESP32 Temperature Sensor
# Reduces false positives for this specific project

[allowlist]
description = "Allowlisted files and patterns"

# Allow example/sample files
paths = [
    '''.env.example''',
    '''device.sample.yaml''',
    '''secrets.example.yaml''',
    '''requirements.txt''',
    '''tests/.*''',
    '''fixtures/.*''',
    '''.*\.md$''',
]

# Allow common test IPs and example values
regexes = [
    '''192\.168\.\d+\.\d+''',  # Private IPs in tests
    '''10\.\d+\.\d+\.\d+''',   # Private IPs in tests
    '''password["']\s*:\s*["']your_''',  # Example passwords
    '''password["']\s*:\s*["']YOUR_''',  # Example passwords
    '''ssid["']\s*:\s*["']YOUR_''',     # Example SSIDs
]

# Extend the default rules but skip these file types
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(?:api[_\s]?key|apikey)["']?\s*[:=]\s*["']([a-zA-Z0-9]{32,})["']'''
secretGroup = 1
entropy = 4.5
keywords = ["api", "key"]

# Skip these paths for this rule
[rules.allowlist]
paths = [
    '''tests/.*''',
    '''.*\.example''',
    '''.*\.sample''',
]

# Custom rule for MQTT passwords
[[rules]]
id = "mqtt-password"
description = "MQTT Password"
regex = '''mqtt[_\s]?pass(?:word)?["']?\s*[:=]\s*["']([^"']+)["']'''
secretGroup = 1
keywords = ["mqtt", "pass"]

[rules.allowlist]
regexes = [
    '''your_mqtt_password''',
    '''mqtt_password_here''',
    '''\$\{MQTT_PASSWORD\}''',
]

# Custom rule for WiFi passwords
[[rules]]
id = "wifi-password"
description = "WiFi Password"
regex = '''wifi[_\s]?pass(?:word)?["']?\s*[:=]\s*["']([^"']+)["']'''
secretGroup = 1
keywords = ["wifi", "pass"]

[rules.allowlist]
regexes = [
    '''your_wifi_password''',
    '''YOUR_PASS''',
    '''\$\{WIFI_PASSWORD\}''',
]