[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "W", "I"]
ignore = []
exclude = [
    ".git",
    ".github",
    "firmware/arduino/src/icons_generated.h",
]

[tool.ruff.isort]
known-first-party = ["scripts", "tests"]
force-sort-within-sections = true


[tool.mypy]
python_version = "3.11"
mypy_path = ["typings"]
namespace_packages = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = false
no_implicit_optional = true
strict_optional = true
