sonar.projectKey=jtn0123_ESP32-Temp-Sensor
sonar.organization=jtn0123ismysonar

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/dist/**,**/.venv/**,**/build/**,**/*.c,**/*.cpp,**/*.h,**/*.hpp
sonar.test.inclusions=**/test_*.py,**/tests/**

sonar.python.version=3.11,3.12
