# Home Assistant automation: publish outdoor metrics to MQTT (retained)
#
# - Publishes outdoor temperature/humidity/condition to topics that the room node
#   subscribes to by default: home/outdoor/{temp,hum,weather}
# - Marked retained so values are available immediately after the node wakes.
# - Adjust entity_id and base topics to match your setup.

alias: Publish outdoor to MQTT (room node)
id: publish_outdoor_to_mqtt_room_node
mode: restart
trigger:
  - platform: state
    entity_id:
      - sensor.outdoor_temperature
      - sensor.outdoor_humidity
      - weather.home
action:
  - variables:
      base: home/outdoor
      t: "{{ states('sensor.outdoor_temperature') }}"
      h: "{{ states('sensor.outdoor_humidity') }}"
      w: "{{ state_attr('weather.home','state') or states('weather.home') }}"
  - service: mqtt.publish
    data:
      topic: "{{ base }}/temp"
      payload: "{{ t }}"
      retain: true
  - service: mqtt.publish
    data:
      topic: "{{ base }}/hum"
      payload: "{{ h }}"
      retain: true
  - service: mqtt.publish
    data:
      topic: "{{ base }}/weather"
      payload: "{{ w }}"
      retain: true


