[package]
name = "room-node"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-sys = { version = "*", features = ["binstart"] }
esp-idf-hal = "*"
embedded-graphics = "0.8"
epd-waveshare = "0.6"
heapless = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"


