room_name: "Office"
wake_interval: "2h"           # 1h|2h|4h
full_refresh_every: 12         # partials between full clears
# Optional: firmware version string for HA device registry (sw_version). If not set,
# it falls back to FW_VERSION env var, then `git describe` or short commit, else 'dev'.
# fw_version: "1.0.0"
outside_source: "mqtt"        # ha|mqtt (v1 defaults to MQTT)
ha_entities:
  outdoor_temp: sensor.outdoor_temperature
  outdoor_hum:  sensor.outdoor_humidity
  weather:      weather.home
mqtt:
  host: 192.168.1.10
  port: 1883
  user: your_mqtt_user
  password: your_mqtt_password
  base_topics:
    publish: sensors/office
    subscribe: home/outdoor
wifi:
  ssid: YOUR_SSID
  password: YOUR_PASS
  # Optional: improve connect speed and stability
  # static:
  #   ip: 192.168.1.50
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 1.1.1.1
  #   dns2: 8.8.8.8
  # bssid: "aa:bb:cc:dd:ee:ff"  # AP MAC to fast connect
  # channel: 6                   # AP channel to fast connect
  # country: "US"               # Country code for legal channels (US/EU/...)
thresholds:
  temp_degC: 0.1
  rh_pct: 1
battery:
  capacity_mAh: 3500
  sleep_current_mA: 0.09
  active_current_mA: 80
  # If not using MAX17048, you can wire the battery to an ADC pin and set divider
  # adc_pin: 5
  # divider: 2.0
  # adc_max: 4095
  # adc_ref: 3.3
  # Percentage threshold considered "low battery" for UI/alerts
  low_pct: 20


