#!/bin/bash

# Script to safely rotate credentials after potential exposure

echo "🔐 Credential Rotation Helper"
echo "============================="
echo ""
echo "⚠️  SECURITY ALERT: Your credentials may have been exposed!"
echo ""
echo "Credentials found in config/device.yaml:"
echo "  - WiFi SSID: ***REDACTED-SSID***"
echo "  - WiFi Password: ***REDACTED-WIFI-PASS-PREFIX*** (hidden)"
echo "  - MQTT User: mqtt-client"
echo "  - MQTT Password: ***REDACTED-MQTT-PASS-PREFIX*** (hidden)"
echo "  - MQTT Host: ***REDACTED-BROKER-HOST***"
echo ""
echo "IMMEDIATE ACTIONS REQUIRED:"
echo "1. Change your WiFi password immediately"
echo "2. Change your MQTT broker password"
echo "3. Update any other services using these credentials"
echo ""
echo "AFTER CHANGING PASSWORDS:"
echo ""
echo "1. Create a .env file (never commit this!):"
echo "   cp .env.example .env"
echo "   nano .env"
echo ""
echo "2. Add your NEW credentials to .env:"
echo "   WIFI_SSID=***REDACTED-SSID***"
echo "   WIFI_PASSWORD=your_new_wifi_password"
echo "   MQTT_USER=mqtt-client"
echo "   MQTT_PASSWORD=your_new_mqtt_password"
echo ""
echo "3. Remove the exposed device.yaml:"
echo "   rm config/device.yaml"
echo "   cp config/device.sample.yaml config/device.yaml"
echo ""
echo "4. Edit config/device.yaml and remove ALL passwords"
echo "   (they'll come from .env instead)"
echo ""
echo "5. Regenerate config:"
echo "   python3 scripts/gen_device_header.py"
echo ""
echo "6. If you ever committed passwords to git, clean history:"
echo "   git filter-branch --force --index-filter \\"
echo "     'git rm --cached --ignore-unmatch config/device.yaml' \\"
echo "     --prune-empty --tag-name-filter cat -- --all"
echo ""
echo "7. Force push to update remote (if needed):"
echo "   git push --force --all"
echo "   git push --force --tags"
echo ""
echo "Press Enter to acknowledge you've read this..."
read

# Backup current config
if [ -f "config/device.yaml" ]; then
    echo "Backing up current device.yaml to device.yaml.backup.INSECURE"
    cp config/device.yaml config/device.yaml.backup.INSECURE
    echo "⚠️  This backup contains passwords - delete after migration!"
fi

# Create safe device.yaml from sample
echo ""
echo "Creating safe device.yaml from sample..."
cp config/device.sample.yaml config/device.yaml.new
echo "✅ Created config/device.yaml.new (without passwords)"
echo ""
echo "Next steps:"
echo "1. Review config/device.yaml.new"
echo "2. Create .env with your NEW passwords"
echo "3. mv config/device.yaml.new config/device.yaml"
echo "4. rm config/device.yaml.backup.INSECURE (after confirming .env works)"
echo ""
echo "Remember: NEVER commit .env or any file with real passwords!"