// Alias non-RECT names to generated RECT_* constants
#pragma once

#include "display_layout.h"

#define HEADER_NAME RECT_HEADER_NAME
#define HEADER_VERSION RECT_HEADER_VERSION
#define HEADER_TIME_CENTER RECT_HEADER_TIME_CENTER

#define INSIDE_TEMP RECT_INSIDE_TEMP
#define INSIDE_HUMIDITY RECT_INSIDE_HUMIDITY
#define INSIDE_PRESSURE RECT_INSIDE_PRESSURE

#define OUT_TEMP RECT_OUT_TEMP
#define WEATHER_ICON RECT_WEATHER_ICON
#define OUT_WEATHER RECT_OUT_WEATHER
#define OUT_PRESSURE RECT_OUT_PRESSURE
#define OUT_HUMIDITY RECT_OUT_HUMIDITY
#define OUT_WIND RECT_OUT_WIND

#define FOOTER_STATUS RECT_FOOTER_STATUS
#define FOOTER_WEATHER RECT_FOOTER_WEATHER


