// AUTO-GENERATED by scripts/gen_layout_header.py — DO NOT EDIT
// source: /Users/justin/Documents/Github/ESP32-Temp-Sensor/config/display_geometry.json
// md5: 6bd893f2d216ab4010b61ef316be9d0b
#pragma once

// Display dimensions
#ifndef EINK_WIDTH
#define EINK_WIDTH 250
#endif
#ifndef EINK_HEIGHT
#define EINK_HEIGHT 122
#endif

// Partial update windows (x, y, w, h) — generated from display_geometry.json
static constexpr int HEADER_NAME[4] = {   6,   2, 160, 14};
static constexpr int HEADER_TIME[4] = { 172,   2,  72, 14};
static constexpr int INSIDE_TEMP[4] = {   6,  36, 118, 28};
static constexpr int INSIDE_RH[4] = {   6,  66, 118, 14};
static constexpr int INSIDE_TIME[4] = {   6,  82, 118, 12};
static constexpr int OUT_TEMP[4] = { 131,  36,  90, 28};
static constexpr int OUT_ICON[4] = { 210,  22,  28, 28};
static constexpr int OUT_ROW1_L[4] = { 131,  66,  44, 12};
static constexpr int OUT_ROW1_R[4] = { 177,  66,  64, 12};
static constexpr int OUT_ROW2_L[4] = { 131,  84,  44, 12};
static constexpr int OUT_ROW2_R[4] = { 177,  84,  44, 12};
static constexpr int STATUS[4] = {   6, 112, 238, 10};
static constexpr int STATUS_[4]     = {   6, 112, 238, 10};

enum WeatherIconId {
    ICON_CLEAR = 0,
    ICON_PARTLY,
    ICON_CLOUDY,
    ICON_RAIN,
    ICON_STORM,
    ICON_SNOW,
    ICON_FOG,
};

// Compile-time layout sanity checks (widths/heights within bounds)
static_assert(HEADER_NAME[0] >= 0 && HEADER_NAME[1] >= 0, "HEADER_NAME origin");
static_assert(6 + 160 <= EINK_WIDTH,  "HEADER_NAME width");
static_assert(2 + 14 <= EINK_HEIGHT, "HEADER_NAME height");
static_assert(HEADER_TIME[0] >= 0 && HEADER_TIME[1] >= 0, "HEADER_TIME origin");
static_assert(172 + 72 <= EINK_WIDTH,  "HEADER_TIME width");
static_assert(2 + 14 <= EINK_HEIGHT, "HEADER_TIME height");
static_assert(INSIDE_TEMP[0] >= 0 && INSIDE_TEMP[1] >= 0, "INSIDE_TEMP origin");
static_assert(6 + 118 <= EINK_WIDTH,  "INSIDE_TEMP width");
static_assert(36 + 28 <= EINK_HEIGHT, "INSIDE_TEMP height");
static_assert(INSIDE_RH[0] >= 0 && INSIDE_RH[1] >= 0, "INSIDE_RH origin");
static_assert(6 + 118 <= EINK_WIDTH,  "INSIDE_RH width");
static_assert(66 + 14 <= EINK_HEIGHT, "INSIDE_RH height");
static_assert(INSIDE_TIME[0] >= 0 && INSIDE_TIME[1] >= 0, "INSIDE_TIME origin");
static_assert(6 + 118 <= EINK_WIDTH,  "INSIDE_TIME width");
static_assert(82 + 12 <= EINK_HEIGHT, "INSIDE_TIME height");
static_assert(OUT_TEMP[0] >= 0 && OUT_TEMP[1] >= 0, "OUT_TEMP origin");
static_assert(131 + 90 <= EINK_WIDTH,  "OUT_TEMP width");
static_assert(36 + 28 <= EINK_HEIGHT, "OUT_TEMP height");
static_assert(OUT_ICON[0] >= 0 && OUT_ICON[1] >= 0, "OUT_ICON origin");
static_assert(210 + 28 <= EINK_WIDTH,  "OUT_ICON width");
static_assert(22 + 28 <= EINK_HEIGHT, "OUT_ICON height");
static_assert(OUT_ROW1_L[0] >= 0 && OUT_ROW1_L[1] >= 0, "OUT_ROW1_L origin");
static_assert(131 + 44 <= EINK_WIDTH,  "OUT_ROW1_L width");
static_assert(66 + 12 <= EINK_HEIGHT, "OUT_ROW1_L height");
static_assert(OUT_ROW1_R[0] >= 0 && OUT_ROW1_R[1] >= 0, "OUT_ROW1_R origin");
static_assert(177 + 64 <= EINK_WIDTH,  "OUT_ROW1_R width");
static_assert(66 + 12 <= EINK_HEIGHT, "OUT_ROW1_R height");
static_assert(OUT_ROW2_L[0] >= 0 && OUT_ROW2_L[1] >= 0, "OUT_ROW2_L origin");
static_assert(131 + 44 <= EINK_WIDTH,  "OUT_ROW2_L width");
static_assert(84 + 12 <= EINK_HEIGHT, "OUT_ROW2_L height");
static_assert(OUT_ROW2_R[0] >= 0 && OUT_ROW2_R[1] >= 0, "OUT_ROW2_R origin");
static_assert(177 + 44 <= EINK_WIDTH,  "OUT_ROW2_R width");
static_assert(84 + 12 <= EINK_HEIGHT, "OUT_ROW2_R height");
static_assert(STATUS[0] >= 0 && STATUS[1] >= 0, "STATUS origin");
static_assert(6 + 238 <= EINK_WIDTH,  "STATUS width");
static_assert(112 + 10 <= EINK_HEIGHT, "STATUS height");
static_assert(STATUS_[0] + STATUS_[2] <= EINK_WIDTH,  "STATUS_ width");

