// AUTO-GENERATED by scripts/gen_ui.py — DO NOT EDIT
// source: /Users/justin/Documents/Github/ESP32-Temp-Sensor/config/ui_spec.json
#pragma once

// Basic UI spec info
namespace ui {
struct SpecInfo { int canvas_w; int canvas_h; };
static constexpr SpecInfo SPEC{ 250, 122 };
enum VariantId {
    UIVAR_V1 = 0,
};
}

