// AUTO-GENERATED by scripts/gen_ui.py — DO NOT EDIT
// source: /Users/justin/Documents/Github/ESP32-Temp-Sensor/config/ui_spec.json
// Copyright 2024 Justin
#include "ui_generated.h"

// Placeholder implementation. Full draw ops will be generated in a later step.
