// AUTO-GENERATED by scripts/gen_ui.py — DO NOT EDIT
// source: /Users/justin/Documents/Github/ESP32-Temp-Sensor/config/ui_spec.json
// schema: ui-spec@1
#pragma once

// Basic UI spec info
namespace ui {
struct SpecInfo { int canvas_w; int canvas_h; };
static constexpr SpecInfo SPEC{ 250, 122 };
enum VariantId {
    UIVAR_V1 = 0,
    UIVAR_V1_MISSING_ALL = 1,
    UIVAR_V1_MISSING_INSIDE = 2,
    UIVAR_V1_MISSING_OUTSIDE = 3,
    UIVAR_V2_1_GRID = 4,
    UIVAR_V2_1_MISSING_ALL = 5,
    UIVAR_V2_1_MISSING_INSIDE = 6,
    UIVAR_V2_1_MISSING_OUTSIDE = 7,
};
}

// Icon tokens: weather-cloudy weather-fog weather-lightning weather-night weather-partly-cloudy weather-pouring weather-snowy weather-sunny weather-windy-variant
