// AUTO-GENERATED by scripts/gen_ui.py — DO NOT EDIT
// source: /Users/justin/Documents/Github/ESP32-Temp-Sensor/config/ui_spec.json
// schema: ui-spec@1
// Copyright 2024 Justin
#include "ui_generated.h"

// Placeholder implementation. Full draw ops will be generated in a later step.
// weather-sunny weather-partly-cloudy weather-cloudy weather-fog
// weather-pouring weather-snowy weather-lightning weather-night
// weather-night-partly-cloudy weather-windy-variant
// icons: weather-lightning weather-pouring weather-snowy weather-fog weather-partly-cloudy weather-cloudy weather-night weather-windy-variant weather-snowy weather-cloudy weather-sunny weather-sunny
