// AUTO-GENERATED by scripts/gen_ui.py — DO NOT EDIT
// source: config/ui_spec.json
#include <cstddef>
#include "ui_ops_generated.h"

namespace ui {

const int kRectTable[RECT__COUNT][4] = {
    {6, 88, 118, 12},  // RECT_FOOTER_BATTERY
    {6, 104, 120, 14},  // RECT_FOOTER_IP
    {174, 90, 72, 30},  // RECT_FOOTER_WEATHER
    {0, 0, 250, 14},  // RECT_HEADER_BAND_V3
    {6, 2, 90, 14},  // RECT_HEADER_NAME
    {6, 2, 82, 12},  // RECT_HEADER_NAME_V3
    {100, 2, 50, 14},  // RECT_HEADER_TIME_CENTER
    {88, 2, 94, 12},  // RECT_HEADER_UPDATED_V3
    {172, 2, 72, 14},  // RECT_HEADER_VERSION
    {184, 2, 60, 12},  // RECT_HEADER_VERSION_V3
    {6, 60, 118, 10},  // RECT_INSIDE_HUMIDITY
    {6, 18, 60, 14},  // RECT_INSIDE_LABEL
    {10, 18, 42, 10},  // RECT_INSIDE_LABEL_V3
    {6, 70, 118, 10},  // RECT_INSIDE_PRESSURE
    {60, 64, 62, 10},  // RECT_INSIDE_PRESS_V3
    {8, 64, 58, 10},  // RECT_INSIDE_RH_V3
    {6, 16, 50, 12},  // RECT_INSIDE_TAB_V3
    {6, 34, 118, 26},  // RECT_INSIDE_TEMP
    {6, 28, 118, 32},  // RECT_INSIDE_TEMP_V3
    {129, 18, 70, 14},  // RECT_OUTSIDE_LABEL
    {133, 18, 50, 10},  // RECT_OUTSIDE_LABEL_V3
    {129, 16, 58, 12},  // RECT_OUTSIDE_TAB_V3
    {131, 64, 44, 10},  // RECT_OUT_HUMIDITY
    {131, 74, 110, 10},  // RECT_OUT_PRESSURE
    {131, 74, 110, 10},  // RECT_OUT_PRESS_V3
    {131, 64, 52, 10},  // RECT_OUT_RH_V3
    {129, 36, 94, 28},  // RECT_OUT_TEMP
    {128, 28, 118, 32},  // RECT_OUT_TEMP_V3
    {177, 64, 64, 10},  // RECT_OUT_WIND
    {185, 64, 58, 10},  // RECT_OUT_WIND_V3
    {140, 90, 30, 30},  // RECT_WEATHER_ICON
};

const UiOpHeader kOps_chrome[] = {
    { OP_LINE, 255, 0, 0, 0, 0, 249, 0, NULL, NULL },
    { OP_LINE, 255, 0, 0, 0, 121, 249, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 0, 0, 0, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 249, 0, 249, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 125, 14, 125, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 1, 84, 249, 84, NULL, NULL },
};
const int kOps_chrome_count = sizeof(kOps_chrome)/sizeof(kOps_chrome[0]);

const UiOpHeader kOps_header_centered[] = {
    { OP_LINE, 255, 0, 0, 1, 14, 249, 14, NULL, NULL },
    { OP_TEXT, 4, 1, 0, 0, 0, 0, 0, "{room_name}", NULL },
    { OP_TEXTCENTEREDIN, 6, 3, 2, 1, 0, 0, 0, "{time_hhmm}", NULL },
    { OP_TEXT, 8, 3, 1, 0, 0, 0, 0, "v{fw_version}", NULL },
};
const int kOps_header_centered_count = sizeof(kOps_header_centered)/sizeof(kOps_header_centered[0]);

const UiOpHeader kOps_header[] = {
    { OP_LINE, 255, 0, 0, 1, 14, 249, 14, NULL, NULL },
    { OP_TEXT, 4, 1, 0, 0, 0, 0, 0, "{room_name}", NULL },
    { OP_TIMERIGHT, 8, 3, 1, 0, 0, 0, 0, "time_hhmm", NULL },
};
const int kOps_header_count = sizeof(kOps_header)/sizeof(kOps_header[0]);

const UiOpHeader kOps_inside[] = {
    { OP_TEXT, 11, 1, 2, 0, 0, 0, 0, "INSIDE", NULL },
    { OP_TEMPGROUPCENTERED, 17, 0, 2, 0, 0, 0, 0, "inside_temp_f", NULL },
    { OP_TEXT, 10, 2, 0, 0, 0, 0, 0, "{inside_hum_pct}% RH", NULL },
    { OP_TEXT, 13, 2, 0, 0, 0, 0, 0, "{pressure_hpa:.1f} hPa", "pressure_hpa" },
};
const int kOps_inside_count = sizeof(kOps_inside)/sizeof(kOps_inside[0]);

const UiOpHeader kOps_outside[] = {
    { OP_TEXT, 19, 1, 2, 0, 0, 0, 0, "OUTSIDE", NULL },
    { OP_TEMPGROUPCENTERED, 26, 0, 2, 0, 0, 0, 0, "outside_temp_f", NULL },
    { OP_ICONIN, 30, 0, 0, 0, 0, 0, 0, "weather", NULL },
    { OP_TEXT, 23, 2, 0, 0, 0, 0, 0, "{outside_pressure_hpa:.0f} hPa", "outside_pressure_hpa" },
    { OP_TEXT, 22, 2, 0, 0, 0, 0, 0, "{outside_hum_pct}% RH", "outside_hum_pct" },
    { OP_TEXT, 28, 2, 0, 0, 0, 0, 0, "{wind_mps->mph:.1f} mph", "wind_mps" },
};
const int kOps_outside_count = sizeof(kOps_outside)/sizeof(kOps_outside[0]);

const UiOpHeader kOps_footer_split[] = {
    { OP_BATTERYGLYPH, 0, 0, 0, 8, 90, 13, 7, "battery_percent", NULL },
    { OP_TEXT, 0, 2, 1, 0, 0, 0, 0, "{battery_voltage:.2f}V {battery_percent}% ~{days}d", NULL },
    { OP_TEXT, 1, 2, 2, 0, 0, 0, 0, "IP {ip}", NULL },
    { OP_TEXTCENTEREDIN, 2, 2, 2, 10, 0, 0, 0, "{weather_short}", NULL },
};
const int kOps_footer_split_count = sizeof(kOps_footer_split)/sizeof(kOps_footer_split[0]);

const UiOpHeader kOps_chrome_v3[] = {
    { OP_LINE, 255, 0, 0, 0, 0, 249, 0, NULL, NULL },
    { OP_LINE, 255, 0, 0, 0, 121, 249, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 0, 0, 0, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 249, 0, 249, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 1, 14, 249, 14, NULL, NULL },
    { OP_LINE, 255, 0, 0, 125, 14, 125, 121, NULL, NULL },
    { OP_LINE, 255, 0, 0, 1, 84, 249, 84, NULL, NULL },
};
const int kOps_chrome_v3_count = sizeof(kOps_chrome_v3)/sizeof(kOps_chrome_v3[0]);

const UiOpHeader kOps_header_v3[] = {
    { OP_FILL, 3, 0, 0, 0, 0, 0, 0, NULL, NULL },
    { OP_TEXT, 5, 1, 0, 0, 0, 0, 1, "{room_name}", NULL },
    { OP_TEXTCENTEREDIN, 7, 3, 2, 1, 0, 0, 1, "{date_mmmdd} {time_hhmm}", NULL },
    { OP_TEXT, 9, 3, 1, 0, 0, 0, 1, "v{fw_version}", NULL },
};
const int kOps_header_v3_count = sizeof(kOps_header_v3)/sizeof(kOps_header_v3[0]);

const UiOpHeader kOps_inside_v3[] = {
    { OP_FILL, 16, 0, 0, 0, 0, 0, 0, NULL, NULL },
    { OP_TEXT, 12, 2, 0, 0, 0, 0, 1, "INSIDE", NULL },
    { OP_TEMPGROUPCENTERED, 18, 0, 2, 0, 0, 0, 0, "inside_temp_f", NULL },
    { OP_TEXT, 15, 2, 0, 0, 0, 0, 0, "{inside_hum_pct}% RH", NULL },
    { OP_TEXT, 14, 2, 1, 0, 0, 0, 0, "{pressure_hpa:.1f} hPa", "pressure_hpa" },
};
const int kOps_inside_v3_count = sizeof(kOps_inside_v3)/sizeof(kOps_inside_v3[0]);

const UiOpHeader kOps_outside_v3[] = {
    { OP_FILL, 21, 0, 0, 0, 0, 0, 0, NULL, NULL },
    { OP_TEXT, 20, 2, 0, 0, 0, 0, 1, "OUTSIDE", NULL },
    { OP_TEMPGROUPCENTERED, 27, 0, 2, 0, 0, 0, 0, "outside_temp_f", NULL },
    { OP_ICONIN, 30, 0, 0, 0, 0, 0, 0, "weather", NULL },
    { OP_TEXT, 25, 2, 0, 0, 0, 0, 0, "{outside_hum_pct}% RH", "outside_hum_pct" },
    { OP_TEXT, 29, 2, 1, 0, 0, 0, 0, "{wind_mps->mph:.1f} mph", "wind_mps" },
    { OP_TEXT, 24, 2, 0, 0, 0, 0, 0, "{outside_pressure_hpa:.0f} hPa", "outside_pressure_hpa" },
};
const int kOps_outside_v3_count = sizeof(kOps_outside_v3)/sizeof(kOps_outside_v3[0]);

const UiOpHeader kOps_footer_v3[] = {
    { OP_BATTERYGLYPH, 255, 0, 0, 0, 0, 13, 7, "battery_percent", NULL },
    { OP_TEXT, 255, 2, 0, 0, 0, 0, 0, "{battery_percent}%  ~{days}d", NULL },
    { OP_ICONIN, 255, 0, 0, 0, 0, 0, 0, "weather", NULL },
    { OP_TEXTCENTEREDIN, 255, 2, 2, 12, 0, 0, 0, "{weather_short}", NULL },
};
const int kOps_footer_v3_count = sizeof(kOps_footer_v3)/sizeof(kOps_footer_v3[0]);

const ComponentOps kVariant_v2_ops[] = {
    { kOps_chrome, kOps_chrome_count, "chrome" },
    { kOps_header_centered, kOps_header_centered_count, "header_centered" },
    { kOps_inside, kOps_inside_count, "inside" },
    { kOps_outside, kOps_outside_count, "outside" },
    { kOps_footer_split, kOps_footer_split_count, "footer_split" },
};
const int kVariant_v2_ops_count = sizeof(kVariant_v2_ops)/sizeof(kVariant_v2_ops[0]);

const ComponentOps kVariant_v3_ops[] = {
    { kOps_chrome_v3, kOps_chrome_v3_count, "chrome_v3" },
    { kOps_header_v3, kOps_header_v3_count, "header_v3" },
    { kOps_inside_v3, kOps_inside_v3_count, "inside_v3" },
    { kOps_outside_v3, kOps_outside_v3_count, "outside_v3" },
    { kOps_footer_split, kOps_footer_split_count, "footer_split" },
};
const int kVariant_v3_ops_count = sizeof(kVariant_v3_ops)/sizeof(kVariant_v3_ops[0]);

const ComponentOps* get_variant_ops(uint8_t variantId, int* outCount){
  if (variantId == 0) { if(outCount) *outCount = kVariant_v2_ops_count; return kVariant_v2_ops; }
  else if (variantId == 1) { if(outCount) *outCount = kVariant_v3_ops_count; return kVariant_v3_ops; }
  if(outCount) *outCount = 0; return nullptr;
}

} // namespace ui
