name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: pip install -U platformio pyyaml
      - name: Generate device header
        run: python scripts/gen_device_header.py
      - name: Build firmware
        working-directory: firmware/arduino
        run: pio run

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow pytest pyyaml
          pip install playwright pytest-playwright
          python -m playwright install --with-deps chromium
      - name: Run tests
        run: pytest -q

  esphome-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ESPHome
        run: pip install -U esphome
      - name: Validate ESPHome config
        working-directory: firmware/esphome
        run: |
          cp secrets.example.yaml secrets.yaml
          esphome config room_node.yaml

