name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install -U platformio
      - name: Build firmware
        working-directory: firmware/arduino
        run: pio run
      - name: Run Python tests
        run: |
          pip install -U pillow pytest pyyaml
          pytest -q

