name: mqtt-ci

on:
  push:
  pull_request:

jobs:
  itest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install mosquitto and clients
        run: |
          sudo apt-get update
          sudo apt-get install -y mosquitto mosquitto-clients

      - name: Start Mosquitto broker
        shell: bash
        run: |
          mosquitto -c "$GITHUB_WORKSPACE/.github/mosquitto/mosquitto.conf" -v &
          # Wait for port
          timeout 20 bash -c 'until echo > /dev/tcp/127.0.0.1/1883; do sleep 0.2; done'

      - name: Simulate HA birth
        run: mosquitto_pub -h 127.0.0.1 -t homeassistant/status -m online

      - name: Run MQTT integration test with live subscribe
        env:
          MQTT_HOST: 127.0.0.1
          MQTT_PORT: 1883
        shell: bash
        run: |
          set -euo pipefail
          mosquitto_sub -h 127.0.0.1 -t 'homeassistant/#' -v | sed -u "s/^/[SUB] /" &
          sub_pid=$!
          python3 scripts/test_mqtt_integration.py
          kill $sub_pid || true

      - name: Run pytest birth/rediscovery test against broker
        env:
          MQTT_HOST: 127.0.0.1
          MQTT_PORT: 1883
        run: pytest -q tests/test_mqtt_birth.py


