name: Lint (ruff)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Ruff lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install ruff
        run: pip install --upgrade ruff

      - name: Print ruff version and show pyproject.toml
        run: |
          ruff --version
          echo "--- pyproject.toml ---"
          sed -n '1,240p' pyproject.toml || true

      - name: Run ruff check
        run: ruff check .


